name: build
on: [pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Library
        run: cd proto && make
      - name: Replace angle brackets
        run: sed -i '/^#include/s/[<>]/"/g' ./dist/message.pb.h
