name: build
on: [pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Protocol Buffers
        run: curl -LJO https://github.com/protocolbuffers/protobuf/releases/download/v3.12.1/protobuf-all-3.12.1.tar.gz && \  
              tar -xvzf protobuf-all-3.12.1.tar.gz && cd protobuf-all-3.12.1.tar.gz && cd configure && make && make check && \  
              sudo make install && sudo ldconfig && sudo ldconfig
      - name: Install Nanopb
        run: git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg && ./bootstrap-vcpkg.sh && \  
            ./vcpkg integrate install && ./vcpkg install nanopb
      - name: Build Library
        run: cd proto && make
      - name: Replace angle brackets
        run: sed -i '/^#include/s/[<>]/"/g' ./dist/message.pb.h
